<?php

use \Nette\Application\Routers;

// Load Nette Framework or autoloader generated by Composer
require __DIR__ . '/../libs/autoload.php';


$configurator = new Nette\Config\Configurator;

// Enable Nette Debugger for error visualisation & logging
//$configurator->setDebugMode(TRUE);
$configurator->enableDebugger(__DIR__ . '/../log');

// Enable RobotLoader - this will load all classes automatically
$configurator->setTempDirectory(__DIR__ . '/../temp');
$configurator->createRobotLoader()
	->addDirectory(__DIR__)
	->addDirectory(__DIR__ . '/../libs')
	->register();

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config/config.neon');
$configurator->addConfig(__DIR__ . '/config/config.local.neon', $configurator::NONE); // none section

Kdyby\BootstrapFormRenderer\DI\RendererExtension::register($configurator);

$container = $configurator->createContainer();


$routers = new Routers\RouteList();
$routers[] = new Routers\Route("commit/<token>/<score>", "API:commit");
$routers[] = new Routers\Route("<presenter>/<action>/[/<id>]", "Score:list");

$container->router = $routers;



return $container;
